name: flutter_ahlib_example
description: Example for flutter_ahlib.

publish_to: 'none'
version: 1.0.1
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ahlib:
    path: ../
  flutter_cache_manager: ^3.3.0
  flutter_staggered_grid_view: ^0.6.2
  logger: ^1.2.2
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
