/// An extension for [bool].
extension BoolExtension on bool {
  /// Returns value generated by [func] if condition is true.
  T? ifTrue<T>(T Function() func, [T Function()? fallbackFunc]) {
    if (this == true) {
      return func.call();
    }
    return fallbackFunc?.call();
  }

  /// Returns value generated by [func] if condition is false.
  T? ifFalse<T>(T Function() func, [T Function()? fallbackFunc]) {
    if (this == false) {
      return func.call();
    }
    return fallbackFunc?.call();
  }

  /// Returns value1 generated by [ifFunc] if condition is true, otherwise returns value2 generated by [elseFunc].
  T ifElse<T>(T Function() ifFunc, T Function() elseFunc) {
    if (this == true) {
      return ifFunc.call();
    }
    return elseFunc.call();
  }
}

/// An extension for [Iterable].
extension IterableExtension<T> on Iterable<T> {
  /// Returns a new list containing totalCount count of the given list.
  List<T> repeat(int totalCount) {
    if (totalCount <= 1) {
      return toList();
    }
    var newList = <T>[];
    for (int i = 0; i < totalCount; i++) {
      for (var item in this) {
        newList.add(item);
      }
    }
    return newList;
  }

  /// Returns a new list with separator build by [builder], between items.
  List<T> separateWithBuilder(T Function(int) builder) {
    if (isEmpty) {
      return <T>[];
    }
    var list = toList();
    return [
      list[0],
      for (var idx = 1; idx < length; idx++) ...[
        builder(idx - 1),
        list[idx],
      ],
    ];
  }

  /// Returns a new list with separator between items.
  List<T> separate(T separator) {
    return separateWithBuilder((_) => separator);
  }

  /// Returns the first element of the collection, or returns null if the collection is empty.
  T? get firstOrNull => isEmpty ? null : first;

  /// Returns the last element of the collection, or returns null if the collection is empty.
  T? get lastOrNull => isEmpty ? null : last;
}

/// An extension for any values, and it only contains kotlin-like [let] function.
extension LetExtension<T extends Object> on T {
  /// Calls given function when current value is not null.
  R let<R>(R Function(T value) func) {
    return func.call(this);
  }
}

/// An extension for [Future], and it only contains kotlin-like [let] function.
extension FutureLetExtension<T extends Object> on Future<T?> {
  /// Calls given function when current value is not null.
  Future<R?> futureLet<R>(R Function(T value) func) async {
    T? value = await this;
    if (value != null) {
      return func.call(value);
    }
    return null;
  }
}
