include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    prefer_single_quotes: true
    avoid_function_literals_in_foreach_calls: false
    prefer_function_declarations_over_variables: false
