name: flutter_ahlib
description: >
  A personal flutter library, contains some useful widgets and utils.
version: 1.2.0
homepage: https://github.com/Aoi-hosizora/flutter_ahlib
repository: https://github.com/Aoi-hosizora/flutter_ahlib

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_staggered_grid_view: ^0.6.1
  http: ^0.13.4
  logger: ^1.1.0
  path: 1.8.0
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
