name: flutter_ahlib
description: >
    AoiHosizora's personal library used in flutter, 
    contains some useful widgets and utils.
version: 1.0.12
homepage: https://github.com/Aoi-hosizora/flutter_ahlib
repository: https://github.com/Aoi-hosizora/flutter_ahlib

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.3.0
  flutter_cache_manager: ^1.4.1
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
